/*
 * Dkron REST API
 *
 * You can communicate with Dkron using a RESTful JSON API over HTTP. Dkron nodes usually listen on port `8080` for API requests. All examples in this section assume that you've found a running leader at `localhost:8080`.  Dkron implements a RESTful JSON API over HTTP to communicate with software clients. Dkron listens in port `8080` by default. All examples in this section assume that you're using the default port.  Default API responses are unformatted JSON add the `pretty=true` param to format the response. 
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dkronclient
import (
	"time"
)
// Job A Job represents a scheduled task to execute.
type Job struct {
	// Name for the job. Use only lower case letters (unicode), digits, underscore and dash.
	Name string `json:"name"`
	// Nice name for the job. Optional.
	Displayname string `json:"displayname,omitempty"`
	// Cron expression for the job.
	Schedule string `json:"schedule"`
	// Timezone where the job will be executed. By default and when field is set to empty string, the job will run in local time.
	Timezone string `json:"timezone,omitempty"`
	// Owner of the job
	Owner string `json:"owner,omitempty"`
	// Email of the owner
	OwnerEmail string `json:"owner_email,omitempty"`
	// Number of successful executions
	SuccessCount int32 `json:"success_count,omitempty"`
	// Number of failed executions
	ErrorCount int32 `json:"error_count,omitempty"`
	// Last time this job executed successfully
	LastSuccess time.Time `json:"last_success,omitempty"`
	// Last time this job failed
	LastError time.Time `json:"last_error,omitempty"`
	// Disabled state of the job
	Disabled bool `json:"disabled,omitempty"`
	// Target nodes tags of this job
	Tags map[string]string `json:"tags,omitempty"`
	// Extra metadata tags for this job
	Metadata map[string]string `json:"metadata,omitempty"`
	// Number of times to retry a failed job execution
	Retries int32 `json:"retries,omitempty"`
	// The name/id of the job that will trigger the execution of this job
	ParentJob string `json:"parent_job,omitempty"`
	// Array containing the jobs that depends on this one
	DependentJobs []string `json:"dependent_jobs,omitempty"`
	// Processor plugins used to process executions results of this job
	Processors map[string]map[string]string `json:"processors,omitempty"`
	// Concurrency policy for the job allow/forbid
	Concurrency string `json:"concurrency,omitempty"`
	// Executor plugin used to run the job
	Executor string `json:"executor,omitempty"`
	// Executor plugin parameters
	ExecutorConfig map[string]string `json:"executor_config,omitempty"`
	// Status of the job
	Status string `json:"status,omitempty"`
}
