/*
 * Dkron REST API
 *
 * You can communicate with Dkron using a RESTful JSON API over HTTP. Dkron nodes usually listen on port `8080` for API requests. All examples in this section assume that you've found a running leader at `localhost:8080`.  Dkron implements a RESTful JSON API over HTTP to communicate with software clients. Dkron listens in port `8080` by default. All examples in this section assume that you're using the default port.  Default API responses are unformatted JSON add the `pretty=true` param to format the response. 
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dkronclient
// Status Status represents details about the node.
type Status struct {
	// Node basic details
	Agent map[string]interface{} `json:"agent,omitempty"`
	// Serf status
	Serf map[string]interface{} `json:"serf,omitempty"`
	// Tags asociated with this node
	Tags map[string]interface{} `json:"tags,omitempty"`
}
