/*
 * Dkron REST API
 *
 * You can communicate with Dkron using a RESTful JSON API over HTTP. Dkron nodes usually listen on port `8080` for API requests. All examples in this section assume that you've found a running leader at `localhost:8080`.  Dkron implements a RESTful JSON API over HTTP to communicate with software clients. Dkron listens in port `8080` by default. All examples in this section assume that you're using the default port.  Default API responses are unformatted JSON add the `pretty=true` param to format the response. 
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dkronclient
import (
	"time"
)
// Execution An execution represents a timed job run.
type Execution struct {
	// job name
	JobName string `json:"job_name,omitempty"`
	// start time of the execution
	StartedAt time.Time `json:"started_at,omitempty"`
	// when the execution finished running
	FinishedAt time.Time `json:"finished_at,omitempty"`
	// the execution run successfuly
	Success bool `json:"success,omitempty"`
	// partial output of the command execution
	Output string `json:"output,omitempty"`
	// name of the node that executed the command
	NodeName string `json:"node_name,omitempty"`
}
