/*
 * Dkron REST API
 *
 * You can communicate with Dkron using a RESTful JSON API over HTTP. Dkron nodes usually listen on port `8080` for API requests. All examples in this section assume that you've found a running leader at `localhost:8080`.  Dkron implements a RESTful JSON API over HTTP to communicate with software clients. Dkron listens in port `8080` by default. All examples in this section assume that you're using the default port.  Default API responses are unformatted JSON add the `pretty=true` param to format the response. 
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dkronclient
// Member A member represents a cluster member node.
type Member struct {
	// Node name
	Name string `json:"Name,omitempty"`
	// IP Address
	Addr string `json:"Addr,omitempty"`
	// Port number
	Port int32 `json:"Port,omitempty"`
	// Tags asociated with this node
	Tags map[string]string `json:"Tags,omitempty"`
	// The serf status of the node see: https://godoc.org/github.com/hashicorp/serf/serf#MemberStatus
	Status int32 `json:"Status,omitempty"`
	// Serf protocol minimum version this node can understand or speak
	ProtocolMin int32 `json:"ProtocolMin,omitempty"`
	// Serf protocol maximum version this node can understand or speak
	ProtocolMax int32 `json:"ProtocolMax,omitempty"`
	// Serf protocol current version this node can understand or speak
	ProtocolCur int32 `json:"ProtocolCur,omitempty"`
	// Serf delegate protocol minimum version this node can understand or speak
	DelegateMin int32 `json:"DelegateMin,omitempty"`
	// Serf delegate protocol maximum version this node can understand or speak
	DelegateMax int32 `json:"DelegateMax,omitempty"`
	// Serf delegate protocol current version this node can understand or speak
	DelegateCur int32 `json:"DelegateCur,omitempty"`
}
